<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <style>
        body{width:100%;height:100%;background:#f9f9fc;}
        .page-404-body{width:524px;margin:0 auto;}
        .text-404-box{font-size:20px;color:#000;text-align:center;}
    </style>
</head>
<body>
    <div class="page-404-body">
        <div class=""><img src="/public/images/404.png" /></div>
        <div class="text-404-box">您要找的页面不见了</div>
    </div>
</body>
</html>